# --- TEMPORADA 2020 (17 ETAPAS COM GRID COMPLETO DE 20 PILOTOS) ---

corridas_2020 = [
    # GP 1: Áustria (Spielberg)
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spielberg", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 2: Estíria (Spielberg 2)
    {"ano": 2020, "circuito": "Estiria", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Estiria", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 3: Hungria (Hungaroring)
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Hungaroring", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 4: Grã-Bretanha (Silverstone)
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone", "piloto": "Hulkenberg", "equipe": "Racing Point", "numero": 27, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 5: 70º Aniversário (Silverstone 2)
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Hulkenberg", "equipe": "Racing Point", "numero": 27, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Silverstone 70", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 6: Espanha (Barcelona)
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Barcelona", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 7: Bélgica (Spa-Francorchamps)
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Spa-Francorchamps", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 8: Itália (Monza)
    {"ano": 2020, "circuito": "Monza", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 7, "pontos": 6, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Monza", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 9: Toscana (Mugello)
    {"ano": 2020, "circuito": "Mugello", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Mugello", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 10: Rússia (Sochi)
    {"ano": 2020, "circuito": "Sochi", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 3, "pontos": 15, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sochi", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 11: Eifel (Nürburgring)
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Hulkenberg", "equipe": "Racing Point", "numero": 27, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 19, "pontos": 0, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Nurburgring", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 12: Portugal (Portimão)
    {"ano": 2020, "circuito": "Portimao", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "George Russell", "equipe": "Williams", "numero": 63, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Portimao", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 13: Emília-Romanha (Imola)
    {"ano": 2020, "circuito": "Imola", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Imola", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 14: Turquia (Istambul)
    {"ano": 2020, "circuito": "Istambul", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 9, "pontos": 2, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Istambul", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 15: Bahrein (Sakhir)
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "George Russell", "equipe": "Williams", "numero": 63, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Sakhir", "piloto": "Grosjean", "equipe": "Haas", "numero": 8, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 16: Sakhir (Anel Externo)
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 8, "pontos": 4, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Aitken", "equipe": "Williams", "numero": 89, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Fittipaldi", "equipe": "Haas", "numero": 51, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Anel Externo Sakhir", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 17: Abu Dhabi (Yas Marina)
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Albon", "equipe": "Red Bull Racing", "numero": 23, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Sainz", "equipe": "McLaren", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Ricciardo", "equipe": "Renault", "numero": 3, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Ocon", "equipe": "Renault", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Stroll", "equipe": "Racing Point", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Kvyat", "equipe": "AlphaTauri", "numero": 26, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Vettel", "equipe": "Ferrari", "numero": 5, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Fittipaldi", "equipe": "Haas", "numero": 51, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2020, "circuito": "Yas Marina", "piloto": "Perez", "equipe": "Racing Point", "numero": 11, "posicao": 20, "pontos": 0, "pole_position": "Não"}
]
