# --- TEMPORADA 2021 (22 ETAPAS COM GRID COMPLETO DE 20 PILOTOS) ---

corridas_2021 = [
    # GP 1: Bahrein (Sakhir)
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sakhir", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 2: Emília-Romanha (Imola)
    {"ano": 2021, "circuito": "Imola", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Imola", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 3: Portugal (Portimão)
    {"ano": 2021, "circuito": "Portimao", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Portimao", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 4: Espanha (Barcelona)
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Barcelona", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 5: Mônaco (Monte Carlo)
    {"ano": 2021, "circuito": "Monaco", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monaco", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 20, "pontos": 0, "pole_position": "Sim"},

    # GP 6: Azerbaijão (Baku)
    {"ano": 2021, "circuito": "Baku", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Baku", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 7: França (Paul Ricard)
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Paul Ricard", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 8: Estíria (Spielberg 1)
    {"ano": 2021, "circuito": "Estiria", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Estiria", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 9: Áustria (Spielberg 2)
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spielberg", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 10: Grã-Bretanha (Silverstone)
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Silverstone", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 20, "pontos": 0, "pole_position": "Sim"},

    # GP 11: Hungria (Hungaroring)
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Hungaroring", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 12: Bélgica (Spa-Francorchamps)
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 12.5, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 2, "pontos": 9, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 3, "pontos": 7.5, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 4, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 5, "pontos": 5, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 6, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 7, "pontos": 3, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 8, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 9, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 10, "pontos": 0.5, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Spa-Francorchamps", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 13: Holanda (Zandvoort)
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Kubica", "equipe": "Alfa Romeo", "numero": 88, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Zandvoort", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 14: Itália (Monza)
    {"ano": 2021, "circuito": "Monza", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Kubica", "equipe": "Alfa Romeo", "numero": 88, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 17, "pontos": 0, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Monza", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 15: Rússia (Sochi)
    {"ano": 2021, "circuito": "Sochi", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 7, "pontos": 6, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Sochi", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 16: Turquia (Istambul)
    {"ano": 2021, "circuito": "Istambul", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Istambul", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 17: EUA (Austin)
    {"ano": 2021, "circuito": "Austin", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Austin", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 18: Cidade do México
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 15, "pontos": 0, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Cidade do Mexico", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 19: São Paulo (Interlagos)
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Interlagos", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 20: Catar (Losail)
    {"ano": 2021, "circuito": "Losail", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Losail", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 21: Arábia Saudita (Jidá)
    {"ano": 2021, "circuito": "Jida", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Jida", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 22: Abu Dhabi (Yas Marina)
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 33, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Tsunoda", "equipe": "AlphaTauri", "numero": 22, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Gasly", "equipe": "AlphaTauri", "numero": 10, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Bottas", "equipe": "Mercedes", "numero": 77, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Alonso", "equipe": "Alpine", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Vettel", "equipe": "Aston Martin", "numero": 5, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Ricciardo", "equipe": "McLaren", "numero": 3, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Mick Schumacher", "equipe": "Haas", "numero": 47, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Latifi", "equipe": "Williams", "numero": 6, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Giovinazzi", "equipe": "Alfa Romeo", "numero": 99, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Russell", "equipe": "Williams", "numero": 63, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Raikkonen", "equipe": "Alfa Romeo", "numero": 7, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2021, "circuito": "Yas Marina", "piloto": "Mazepin", "equipe": "Haas", "numero": 9, "posicao": 20, "pontos": 0, "pole_position": "Não"}
]

