# --- TEMPORADA 2024 (24 ETAPAS COM GRID COMPLETO DE 20 PILOTOS) ---

corridas_2024 = [
    # GP 1: Bahrein (Sakhir)
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 26, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Sakhir", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 2: Arábia Saudita (Jidá)
    {"ano": 2024, "circuito": "Jida", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 16, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Bearman", "equipe": "Ferrari", "numero": 38, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Jida", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 3: Austrália (Melbourne)
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 2, "pontos": 19, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 19, "pontos": 0, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Albert Park", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 4: Japão (Suzuka)
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 26, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Suzuka", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 5: China (Xangai)
    {"ano": 2024, "circuito": "Xangai", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 7, "pontos": 7, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Xangai", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 6: Miami
    {"ano": 2024, "circuito": "Miami", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Miami", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 7: Emília-Romanha (Ímola)
    {"ano": 2024, "circuito": "Imola", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 7, "pontos": 7, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Imola", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 8: Mônaco (Monte Carlo)
    {"ano": 2024, "circuito": "Monaco", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 7, "pontos": 7, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monaco", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 9: Canadá (Montreal)
    {"ano": 2024, "circuito": "Montreal", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 3, "pontos": 15, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 4, "pontos": 13, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Montreal", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 10: Espanha (Barcelona)
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 19, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Barcelona", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 11: Áustria (Spielberg)
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 5, "pontos": 10, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spielberg", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 12: Grã-Bretanha (Silverstone)
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 5, "pontos": 11, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 19, "pontos": 0, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Silverstone", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    # GP 13: Hungria (Hungaroring)
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 8, "pontos": 5, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Hungaroring", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 14: Bélgica (Spa-Francorchamps)
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 15, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 7, "pontos": 7, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Spa-Francorchamps", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 20, "pontos": 0, "pole_position": "Não"}, # Desqualificado pós-corrida

    # GP 15: Holanda (Zandvoort)
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 26, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Sargeant", "equipe": "Williams", "numero": 2, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Zandvoort", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 16: Itália (Monza)
    {"ano": 2024, "circuito": "Monza", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 3, "pontos": 16, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Colapinto", "equipe": "Williams", "numero": 43, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Monza", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 17: Azerbaijão (Baku)
    {"ano": 2024, "circuito": "Baku", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 4, "pontos": 13, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Colapinto", "equipe": "Williams", "numero": 43, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Bearman", "equipe": "Haas", "numero": 50, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Baku", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 18: Singapura (Marina Bay)
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Colapinto", "equipe": "Williams", "numero": 43, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Ricciardo", "equipe": "RB", "numero": 3, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Marina Bay", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 19: EUA (Austin)
    {"ano": 2024, "circuito": "Austin", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 4, "pontos": 12, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Lawson", "equipe": "RB", "numero": 30, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Colapinto", "equipe": "Williams", "numero": 43, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Austin", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 20: Cidade do México
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 16, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Colapinto", "equipe": "Williams", "numero": 43, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Lawson", "equipe": "RB", "numero": 30, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Cidade do Mexico", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 21: São Paulo (Interlagos)
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 26, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 6, "pontos": 8, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Lawson", "equipe": "RB", "numero": 30, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Bearman", "equipe": "Haas", "numero": 50, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Colapinto", "equipe": "Williams", "numero": 43, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Interlagos", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 22: Las Vegas
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 6, "pontos": 9, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Colapinto", "equipe": "Williams", "numero": 43, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Lawson", "equipe": "RB", "numero": 30, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Las Vegas", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 23: Catar (Losail)
    {"ano": 2024, "circuito": "Losail", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 10, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Lawson", "equipe": "RB", "numero": 30, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Colapinto", "equipe": "Williams", "numero": 43, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Losail", "piloto": "Ocon", "equipe": "Alpine", "numero": 31, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 24: Abu Dhabi (Yas Marina)
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Sainz", "equipe": "Ferrari", "numero": 55, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Hamilton", "equipe": "Mercedes", "numero": 44, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Hulkenberg", "equipe": "Haas", "numero": 27, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Zhou", "equipe": "Sauber", "numero": 24, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Doohan", "equipe": "Alpine", "numero": 61, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Magnussen", "equipe": "Haas", "numero": 20, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Lawson", "equipe": "RB", "numero": 30, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Bottas", "equipe": "Sauber", "numero": 77, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Colapinto", "equipe": "Williams", "numero": 43, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2024, "circuito": "Yas Marina", "piloto": "Perez", "equipe": "Red Bull Racing", "numero": 11, "posicao": 20, "pontos": 0, "pole_position": "Não"}


]

