# --- TEMPORADA 2025 (24 ETAPAS COM GRID COMPLETO DE 20 PILOTOS) ---

corridas_2025 = [
    # GP 1: Austrália (Albert Park)
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Albert Park", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 2: China (Xangai)
    {"ano": 2025, "circuito": "Xangai", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Xangai", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 3: Japão (Suzuka)
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Suzuka", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 4: Bahrein (Sakhir)
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Sakhir", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 5: Arábia Saudita (Jeddah)
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Jeddah", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 6: Miami
    {"ano": 2025, "circuito": "Miami", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Miami", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 7: Emília-Romanha (Ímola)
    {"ano": 2025, "circuito": "Imola", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Imola", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 8: Mônaco (Monte Carlo)
    {"ano": 2025, "circuito": "Monaco", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monaco", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 9: Espanha (Catalunha)
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Catalunya", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 10: Canadá (Montreal)
    {"ano": 2025, "circuito": "Montreal", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Montreal", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 11: Áustria (Spielberg)
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spielberg", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 12: Grã-Bretanha (Silverstone)
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Silverstone", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

# GP 13: Bélgica (Spa-Francorchamps)
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Spa-Francorchamps", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 14: Hungria (Hungaroring)
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Hungaroring", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 15: Países Baixos (Zandvoort)
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Zandvoort", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 16: Itália (Monza)
    {"ano": 2025, "circuito": "Monza", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Monza", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 17: Azerbaijão (Baku)
    {"ano": 2025, "circuito": "Baku", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Baku", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 18: Singapura (Marina Bay)
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Marina Bay", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 19: Estados Unidos (Austin)
    {"ano": 2025, "circuito": "Austin", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Austin", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 20: Cidade do México
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Cidade do Mexico", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 21: São Paulo (Interlagos)
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Interlagos", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 22: Las Vegas
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Las Vegas", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 23: Catar (Losail)
    {"ano": 2025, "circuito": "Losail", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Losail", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 24: Abu Dhabi (Yas Marina)
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Doohan", "equipe": "Alpine", "numero": 7, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2025, "circuito": "Yas Marina", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"}
]

