# --- TEMPORADA 2026 (ETAPAS REALIZADAS - GRID COMPLETO) ---

corridas_2026 = [
    # GP 1: Austrália (Melbourne)
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 6, "pontos": 8, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Albert Park", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 20, "pontos": 0, "pole_position": "Não"},

    # GP 2: China (Xangai)
    {"ano": 2026, "circuito": "Xangai", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Xangai", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 18, "pontos": 0, "pole_position": "Não"},

    # GP 3: Japão (Suzuka)
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Norris", "equipe": "McLaren", "numero": 4, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Suzuka", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 4: Miami
    {"ano": 2026, "circuito": "Miami", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Miami", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 5: Canadá (Montreal)
    {"ano": 2026, "circuito": "Montreal", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 19, "pontos": 0, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Montreal", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 21, "pontos": 0, "pole_position": "Não"},

    # GP 6: Mônaco (Monte Carlo)
    {"ano": 2026, "circuito": "Monaco", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monaco", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 7: Espanha (Barcelona - Catalunha)
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 2, "pontos": 18, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Catalunya", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 8: Áustria (Spielberg)
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spielberg", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 9: Grã-Bretanha (Silverstone)
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 4, "pontos": 12, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 15, "pontos": 0, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Silverstone", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 10: Bélgica (Spa-Francorchamps)
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 1, "pontos": 25, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Spa-Francorchamps", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 11: Hungria (Hungaroring)
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Hadjar", "equipe": "RB", "numero": 6, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Hungaroring", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 12: Países Baixos (Zandvoort)
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Zandvoort", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 13: Itália (Monza)
    {"ano": 2026, "circuito": "Monza", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 3, "pontos": 15, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 7, "pontos": 6, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Monza", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 22, "pontos": 0, "pole_position": "Não"},

    # GP 14: Espanha (Madrid)
    {"ano": 2026, "circuito": "Madrid", "piloto": "Antonelli", "equipe": "Mercedes", "numero": 12, "posicao": 1, "pontos": 25, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Verstappen", "equipe": "Red Bull Racing", "numero": 3, "posicao": 2, "pontos": 18, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Norris", "equipe": "McLaren", "numero": 1, "posicao": 3, "pontos": 15, "pole_position": "Sim"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Leclerc", "equipe": "Ferrari", "numero": 16, "posicao": 4, "pontos": 12, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Russell", "equipe": "Mercedes", "numero": 63, "posicao": 5, "pontos": 10, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Lawson", "equipe": "Red Bull Racing", "numero": 30, "posicao": 6, "pontos": 8, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Colapinto", "equipe": "Alpine", "numero": 43, "posicao": 7, "pontos": 6, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Piastri", "equipe": "McLaren", "numero": 81, "posicao": 8, "pontos": 4, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Lindblad", "equipe": "RB", "numero": 41, "posicao": 9, "pontos": 2, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Hulkenberg", "equipe": "Sauber", "numero": 27, "posicao": 10, "pontos": 1, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Ocon", "equipe": "Haas", "numero": 31, "posicao": 11, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Gasly", "equipe": "Alpine", "numero": 10, "posicao": 12, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Bortoleto", "equipe": "Sauber", "numero": 5, "posicao": 13, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Tsunoda", "equipe": "RB", "numero": 22, "posicao": 14, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Albon", "equipe": "Williams", "numero": 23, "posicao": 15, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Bearman", "equipe": "Haas", "numero": 87, "posicao": 16, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Alonso", "equipe": "Aston Martin", "numero": 14, "posicao": 17, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Bottas", "equipe": "Cadillac", "numero": 77, "posicao": 18, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Sainz", "equipe": "Williams", "numero": 55, "posicao": 19, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Pérez", "equipe": "Cadillac", "numero": 11, "posicao": 20, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Stroll", "equipe": "Aston Martin", "numero": 18, "posicao": 21, "pontos": 0, "pole_position": "Não"},
    {"ano": 2026, "circuito": "Madrid", "piloto": "Hamilton", "equipe": "Ferrari", "numero": 44, "posicao": 22, "pontos": 0, "pole_position": "Não"}
]